test1:
	./umlparser.sh tests/test1 parsedGraph1

test2:
	./umlparser.sh tests/test2 parsedGraph2

test3:
	./umlparser.sh tests/test3 parsedGraph3

test4:
	./umlparser.sh tests/test4 parsedGraph4

test5:
	./umlparser.sh tests/test5 parsedGraph5

testAll:
	./umlparser.sh tests/test1 parsedGraph1
	./umlparser.sh tests/test2 parsedGraph2
	./umlparser.sh tests/test3 parsedGraph3
	./umlparser.sh tests/test4 parsedGraph4
	./umlparser.sh tests/test5 parsedGraph5

starbucks:
	./umlparser.sh tests/starbucks starbucks