# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nosql-service-nodeport-1
spec:
  selector:
    app: nosql-pod-1
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30000
      name: admin
    - port: 9090
      targetPort: 9090
      nodePort: 30001
      name: app
  type: NodePort