export const RENDER_TO_PROFILE = "RENDER_TO_PROFILE";
export const FLUSH_USER = "FLUSH_USER";
export const RENDER_TO_RESTAURANT = "RENDER_TO_RESTAURANT";
export const FLUSH_SEARCH = "FLUSH_SEARCH";
export const RENDER_TO_GEOLOCATION ="RENDER_TO_GEOLOCATION";
export const FLUSH_GEOLOCATION = "FLUSH_GEOLOCATION";
export const RENDER_TO_GOOGLE = "RENDER_TO_GOOGLE";
export const FLUSH_GOOGLE = "FLUSH_GOOGLE";

// export const INCREMENT = 'INCREMENT';
// export const DECREMENT = 'DECREMENT';
// export const ADD = 'ADD';
// export const SUBTRACT = 'SUBTRACT';
// export const STORE_RESULT = 'STORE_RESULT';
// export const DELETE_RESULT = 'DELETE_RESULT';